### ISSUE TITLE
The TODO

### ISSUE THREAD

**Issue by IsmailM** [SBCS-Bioinformatics/GEODiver#3]
- [x] My Results Section
- [x] Share Results 

<hr>

- [x] 3D PC Scatter Plot
- [x] Scatter plot different point style

<hr>

- [x] Interaction Networks 
- [x] Interaction Network link to KEGG
- [x] GAGE Parameters (KEGG/GP & Exp Vs EXP / EXP Vs Control & cc/Bp / MF
- [x] Create TSV for Gage toptable
<hr>

- [x] Download all dataset - link to App
- [x] JQ user validation

<hr>
- [x] Deploy on AWS

<hr>
- [x] FAQ
- [x] Compare with Papers
- [x] Documentation

**Comment by IsmailM** [comment]
Done
